### ISSUE TITLE
Malware investigation?

### ISSUE THREAD

**Issue by dylanetaft** [PoC-Consortium/Qbundle#22]
https://www.reddit.com/r/burstcoin/comments/7qfnjy/how_is_it_possible_that_someone_is_stealing_from
Basically, there have been several cases of burst getting stolen from folks.  
(I am d13f00l on those forums)

http://files.getburst.net/QInfo

I've been trying to find out how that is happening, and digging into the source.

Did PoC-Consortium do any auditing of the code of bundled apps?

I did some hash checking - for BlagoMiner and XPlotter, md5s at least match from the files Qbundle would pull from files.getburst.net and official releases on github - however - 

Did PoCC do it's own builds of these apps?  If so, I would be very surprised if the hashes match, exactly.  Compiler cruft, optimization params, etc, may differ which would affect the hashes.

Isn't there potential that exe files on github are compromised from these third party sources?

It's also a bit surprising that the address that has stolen burst has been the same, in several cases.

**Comment by dylanetaft** [comment]
https://www.reddit.com/r/burstcoin/comments/7ovju7/did_i_get_hacked/

Both cases, QBundle was used.  
BlagoMiner seems to have somewhat bad hygiene for managing the password, so that was my initial hunch, folks are having trouble mining and are pasting logs, and getting "hacked", when really the wallet PW can be in the log.

**Comment by Bearcomtech** [comment]
Qbundle is only a wrapper for other tools. Blagos tools will be detected as malware since antivirus companies do not like Miners. I have not done any own builds on the downloads found in Qinfo.
When it comes to Qbundle it is not obfuscated or packed so you are free to use any reflection software to see that it maches my sourcecode.

The problem with stolen accounts was a problem long before qbundle even existed. In most cases i think ppl do no use secure accounts/passphrases and are subjects for virus/malwares from other sites.

**Comment by dylanetaft** [comment]
Thanks - this can be closed.  
It might be worth doing custom builds and putting them in a trusted repository.   I was doing some auditing of underlying tools, like Blago will store a password in a plaintext file for solo miners.  Qbundle will write out that file.

Some of the netcode in Blago was a bit concerning too.  It’s not malicious, but it looks like it could be open to vulnabs if you turn on proxy connections.
