### ISSUE TITLE
After update from 2.1.0 to 2.5.0 wallet mode never loads

### ISSUE THREAD

**Issue by codeknox** [PoC-Consortium/Qbundle#68]
Just updated 2.1.0 to 2.5.0, and when running in Wallet Mode. the main page just shows a "Starting Wallet" message.
My wallet *is* running and I had set it up as a Windows Service on 2.1.0.
If I go to Launcher Mode,I can see the wallet is running and fully synchronized.

Any idea what is going on?

**Comment by HeosSacer** [comment]
Burst as a service is not supported by the Qbundle anymore.
This is some change Quibus did. So I cannot provide an explanation why he dropped this feature.

**Comment by Quibus-burst** [comment]
The feature was droped in 2.5.0b because almost no one got it working corectly. IF the feature is to come back one need to make a major rework and implement proper control mechanisms. What is did to make it work was made in a haste and when looking into the mirror i should not have done it.

You can uninstall the burstservice by opening a commandprompt as admin and type
c:\>sc delete "burst service"

**Comment by HeosSacer** [comment]
I don't know If this resolves your issue. Let us know, if there is still something left to discuss.
